name:                discord-share-save
version:             0.2.0.0
github:              "Webnew-b/discord-share-save"
license:             BSD-3-Clause
author:              "lexon"
maintainer:          "lexonnicely@gmail.com"
copyright:           "2025 lexon"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Webnew-b/discord-share-save#readme>

dependencies:
- base >= 4.13 && < 5
- unix
- discord-haskell
- text
- time
- unliftio
- envy
- tomland
- mtl
- async


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  discord-share-save-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - discord-share-save

tests:
  discord-share-save-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - discord-share-save
